plugins:
  - rubocop-internal_affairs
  - rubocop-guardrails

AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Naming/FileName:
  Exclude:
    - lib/rubocop-guardrails.rb
