Guardrails/NoServiceObjects:
  Enabled: true
  Description: 'Disallows service objects.'
  Include:
    - 'app/services/**/*.rb'

Guardrails/RestfulActions:
  Enabled: true
  Description: 'Prevents non-RESTful controller actions.'
  Include:
    - 'app/controllers/**/*.rb'

Guardrails/RestfulRoutes:
  Enabled: true
  Description: 'Detects non-RESTful route definitions.'
  Include:
    - 'config/routes.rb'
    - 'config/routes/**/*.rb'
